# Generated by Django 4.2 on 2023-09-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.FileField(default='', upload_to='mov/'),
        ),
    ]
