# Generated by Django 4.2 on 2023-09-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_movie_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
