# Generated by Django 4.2 on 2023-09-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
